FILENAME REFFILE '/home/u63433433/wine.csv';
* 'DBMS = type of the file;
* 'OUT'name of the data set;
* 'GETNAMES' = header = yes;
PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV  
	OUT=WORK.IMPORT;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.IMPORT; RUN;

* OR
	PROC IMPORT DATAFILE=REFFILE DBMS=CSV OUT=WORK.IMPORT;